export const Colors = {
    light: {
        background: '#FFFFFF',
        surface: '#F5F5F5',
        card: '#FFFFFF',
        text: '#1A1A1A',
        textSecondary: '#666666',
        primary: '#2563EB',
        primaryDark: '#1E40AF',
        secondary: '#10B981',
        danger: '#EF4444',
        warning: '#F59E0B',
        border: '#E5E5E5',
        success: '#10B981',
        info: '#3B82F6',
    },
    dark: {
        background: '#000000',
        surface: '#1A1A1A',
        card: '#1F1F1F',
        cardElevated: '#2A2A2A',
        text: '#FFFFFF',
        textSecondary: '#9CA3AF',
        textTertiary: '#6B7280',
        primary: '#3B82F6',
        primaryDark: '#2563EB',
        secondary: '#10B981',
        danger: '#EF4444',
        warning: '#F59E0B',
        border: '#2A2A2A',
        success: '#10B981',
        info: '#3B82F6',
        // Status colors
        approved: '#10B981',
        completed: '#3B82F6',
        delayed: '#F59E0B',
        denied: '#EF4444',
        // Icon backgrounds
        iconBlue: '#1E3A8A',
        iconGreen: '#065F46',
        iconOrange: '#92400E',
        iconRed: '#7F1D1D',
        iconPurple: '#581C87',
        iconGray: '#374151',
    },
};

export const Shadows = {
    small: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    medium: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 4,
    },
    large: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 16,
        elevation: 8,
    },
};
